language: python
sudo: false
stages:
  - test

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - stage: test
      python: "3.5"
      dist: xenial
    - python: "3.6"
      dist: xenial
    - python: "3.7"
      dist: xenial
    - python: "3.8"
      dist: xenial

script:
  - python setup.py test
